#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#Para habilitar clipbloard en vmware
#vmware-user-suid-wrapper &

#Para virtualbox clipboard,carpetas compartidas:
VBoxClient --clipboard &
VboxClient --seamless &
VboxClient --draganddrop &

#Para los fondos de pantalla
/usr/bin/feh --bg-fill ~/.config/fondos/fondo1.jpg &

#Para lanzar la polybar
~/.config/polybar/./launch.sh &

#Para la transparencia picom
picom &

#Para quitar el borde de la terminal
bspc config border_width 0

#Para que se vea bien burp y programas java
wmname LG3D &

